package app

import (
	"embed"
	"io/fs"
	"net"
	"net/http"
	"strings"
)

// webUIFS embeds the built web UI (TypeScript + React, bundled by Vite —
// see internal/app/webui-src/) so the shipped binary never needs a build
// step or a runtime network fetch to render /ui. internal/app/webui/dist is
// generated by `npm run build` in webui-src and committed to the repo; see
// internal/app/webui-src/README.md.
//
//go:embed webui/dist
var webUIFS embed.FS

// uiHandler serves the embedded web UI at /ui and /ui/* — index.html at the
// root, everything else (the hashed assets/*.js and assets/*.css Vite
// produces) by path.
func uiHandler() http.Handler {
	sub, err := fs.Sub(webUIFS, "webui/dist")
	if err != nil {
		// Only possible if the embed directive above and this Sub call
		// disagree, which would be a build-time mistake, not a runtime one.
		panic("ui: embed webui/dist: " + err.Error())
	}
	fileServer := http.StripPrefix("/ui", http.FileServer(http.FS(sub)))

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			writeError(w, http.StatusMethodNotAllowed, "invalid_request_error", "method not allowed")
			return
		}
		fileServer.ServeHTTP(w, r)
	})
}

// faviconHandler serves the embedded favicon at /favicon.ico. Browsers
// request this path automatically, unauthenticated, for any page on the
// origin (not just /ui), so it's registered at root rather than under /ui
// and exempted from bearer auth in authMiddleware alongside /health and
// /usage.
func faviconHandler() http.Handler {
	sub, err := fs.Sub(webUIFS, "webui/dist")
	if err != nil {
		panic("ui: embed webui/dist: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(sub))
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			writeError(w, http.StatusMethodNotAllowed, "invalid_request_error", "method not allowed")
			return
		}
		fileServer.ServeHTTP(w, r)
	})
}

// isAdminPath identifies the account-management admin surface: /ui (the web
// UI itself), /accounts* (its account API), and /admin/* (its models and
// connection-info API). These routes get the loopback+Host admin bypass in
// authMiddleware and never get a wildcard CORS header in corsMiddleware —
// see both for why.
func isAdminPath(path string) bool {
	return path == "/ui" || strings.HasPrefix(path, "/ui/") ||
		path == "/accounts" || strings.HasPrefix(path, "/accounts/") ||
		strings.HasPrefix(path, "/admin/")
}

// isLocalAdminRequest reports whether r looks like a genuine same-machine
// browser request to the admin surface, as opposed to a remote page trying
// to reach it via DNS rebinding or a raw cross-origin fetch:
//
//   - the TCP peer (r.RemoteAddr) must be loopback (127.0.0.1 or ::1) — a
//     DNS-rebinding attack can make a browser send a Host header of its
//     choosing, but it cannot make the OS route the TCP connection itself
//     through loopback from a remote attacker's machine;
//   - the Host header must be exactly localhost, 127.0.0.1, or [::1]
//     (with whatever port the server is actually listening on) — this is
//     what stops DNS rebinding: an attacker-controlled hostname that
//     resolves to 127.0.0.1 would satisfy the RemoteAddr check above but
//     fails here;
//   - if an Origin header is present at all (i.e. this is a fetch/XHR, not
//     a plain top-level navigation), it must exactly match
//     scheme://Host — a cross-origin page cannot forge this because the
//     browser sets Origin itself.
func isLocalAdminRequest(r *http.Request) bool {
	remoteHost := r.RemoteAddr
	if host, _, err := net.SplitHostPort(remoteHost); err == nil {
		remoteHost = host
	}
	ip := net.ParseIP(remoteHost)
	if ip == nil || !ip.IsLoopback() {
		return false
	}

	hostHeader := r.Host
	hostname := hostHeader
	if h, _, err := net.SplitHostPort(hostHeader); err == nil {
		hostname = h
	}
	hostname = strings.TrimPrefix(strings.TrimSuffix(hostname, "]"), "[")
	switch hostname {
	case "localhost", "127.0.0.1", "::1":
	default:
		return false
	}

	if origin := r.Header.Get("Origin"); origin != "" {
		scheme := "http"
		if r.TLS != nil {
			scheme = "https"
		}
		if origin != scheme+"://"+hostHeader {
			return false
		}
	}

	return true
}
